[project]
name = "wildfire-meteo"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "uvicorn[standard]",
    "numpy",
    "pandas",
    "xarray",
    "netCDF4",
    "requests",
    "openmeteo-requests",
    "requests-cache",
    "retry-requests",
    "timezonefinder",
    "uv",
]

[tool.setuptools.packages.find]
include = ["api*"]

[tool.setuptools.package-data]
api = ["resources/*.txt"]

[tool.fastapi]
entrypoint = "api.main:app"
